name: Validate Containers

on:
  push:
    branches: [ master, main ]
    paths:
      - 'data/containers/**/*.json'
      - 'examples/containers/**/*.json'
      - 'tests/data/containers/**/*.json'
      - 'schemas/container.schema.json'
      - 'tools/validate_containers.py'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'data/containers/**/*.json'
      - 'examples/containers/**/*.json'
      - 'tests/data/containers/**/*.json'
      - 'schemas/container.schema.json'
      - 'tools/validate_containers.py'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
    
    - name: Validate container files
      run: |
        python tools/validate_containers.py --verbose
    
    - name: Check for invalid containers
      run: |
        if ! python tools/validate_containers.py; then
          echo "❌ Container validation failed!"
          echo "Please ensure all container files follow the v1.0 standard."
          echo "See docs/CONTAINER_STANDARD.md for details."
          exit 1
        fi
        echo "✅ All containers are valid!"
